id: P001744
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:18:06.211444
source_metadata:
  id: bdr:W1KG24644
  title: མ་ཅིག་ལབ་སྒྲོན་གྱི་གཅོད་ཀྱི་འཁྲིད་ཡིག
  author: ''
  volumes:
    939dd7b6010843d4941d39150b4d4a2f:
      image_group_id: I1KG24707
      title: ''
      volume_number: 1
      total_pages: 386
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
